# Use a base image with Java
FROM openjdk:17-jdk-slim

# Set the working directory in docker container
RUN mkdir  ./home/app

# Copy the JAR file path into container
COPY target\classes\com\kamal\quizapp-*.jar app.jar

# Expose the port your app uses
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
